upstream app_api {
  server app:8089;
}

upstream app_oai {
  server app:8082;
}

upstream app_public {
  server app:8081;
}

upstream app_staff {
  server app:8080;
}
  
# SSL certificate and key files
ssl_certificate             /ssl/findingaids_lib_msu_edu_cert.cer;
ssl_certificate_key         /ssl/findingaids.key;

# Recommended SSL configurations
ssl_session_cache shared:SSL:1m;
ssl_session_timeout 5m;
ssl_protocols TLSv1.2 TLSv1.3;
ssl_ciphers HIGH:!aNULL:!MD5;
ssl_prefer_server_ciphers on;
  
charset utf-8;
client_max_body_size 16M;
client_header_buffer_size 16k;
large_client_header_buffers 4 16k;

access_log /dev/stdout;
error_log /dev/stdout info;

proxy_buffer_size       128k;
proxy_buffers           4 256k;
proxy_busy_buffers_size 256k;
proxy_http_version 1.1;
proxy_connect_timeout       180;
proxy_send_timeout          180;
proxy_read_timeout          180;
send_timeout                180;

proxy_set_header        Host               $host;
proxy_set_header        X-Forwarded-For    $proxy_add_x_forwarded_for;
proxy_set_header        X-Forwarded-Host   $host;
proxy_set_header        X-Forwarded-Server $host;
proxy_set_header        X-Forwarded-Proto  $scheme;
proxy_set_header        X-Real-IP          $remote_addr;

server {
  listen 80;
  server_name _;
  return 301 https://$host$request_uri;
}

server {
  listen 443 ssl;
  server_name findingaids.devel.lib.msu.edu findingaids.test.lib.msu.edu;

  location / {
    allow 192.168.0.0/16; # Docker
    allow 35.8.220.0/22; # Library
    allow 35.8.111.192/27; # Conrad
    deny  all;
    proxy_pass http://app_public;
  }

  location /oai {
    allow 192.168.0.0/16; # Docker
    allow 35.8.220.0/22; # Library
    allow 35.8.111.192/27; # Conrad
    deny  all;
    proxy_pass http://app_oai/;
  }

  location /staff/ {
    allow 192.168.0.0/16; # Docker
    allow 35.8.220.0/22; # Library
    allow 35.8.111.192/27; # Conrad
    deny  all;
    proxy_pass http://app_staff;
  }

  location /staff/api/ {
    allow 192.168.0.0/16; # Docker
    allow 35.8.220.0/22; # Library
    allow 35.8.111.192/27; # Conrad
    deny  all;
    proxy_pass http://app_api/;
  }
}

server {
  listen 443 ssl;
  server_name findingaids.lib.msu.edu;

  location / {
    allow all;
    proxy_pass http://app_public;
  }

  location /oai {
    allow all;
    proxy_pass http://app_oai/;
  }

  location /staff/ {
    allow 192.168.0.0/16; # Docker
    allow 35.8.220.0/22; # Library
    allow 35.8.111.192/27; # Conrad
    allow 172.21.0.0/19; # F5 VPN basic
    allow 172.21.32.0/19; # F5 VPN moderate
    allow 172.21.64.0/20; # F5 VPN elevated
    deny  all;
    proxy_pass http://app_staff;
  }

  location /staff/api/ {
    allow 192.168.0.0/16; # Docker
    allow 35.8.220.0/22; # Library
    allow 35.8.111.192/27; # Conrad
    allow 172.21.0.0/19; # F5 VPN basic
    allow 172.21.32.0/19; # F5 VPN moderate
    allow 172.21.64.0/20; # F5 VPN elevated
    deny  all;
    proxy_pass http://app_api/;
  }
}
